# Base configuration for Elasticsearch
parameters:
    env(ELASTICSEARCH_URL): '%env(string:ELASTICSEARCH_DSN)%'
    elasticsearch_dsn: "%env(string:ELASTICSEARCH_URL)%"

ibexa_elasticsearch:
    connections:
        default:
            hosts:
                - "%elasticsearch_dsn%"
