parameters:
    env(DFS_DATABASE_URL): '%env(resolve:DATABASE_URL)%'
    dfs_database_url: '%env(resolve:DFS_DATABASE_URL)%'
    ibexa.io.nfs.adapter.config:
        root: '%kernel.project_dir%/%env(string:DFS_NFS_PATH)%'
        path: '$var_dir$/$storage_dir$/'
        writeFlags: ~
        linkHandling: ~
        permissions: [ ]

# new doctrine connection for the dfs legacy_dfs_cluster metadata handler.
doctrine:
    dbal:
        connections:
            dfs:
                # configure these for your database server
                driver: '%env(string:DFS_DATABASE_DRIVER)%'
                charset: '%env(string:DFS_DATABASE_CHARSET)%'
                default_table_options:
                    charset: '%env(string:DFS_DATABASE_CHARSET)%'
                    collate: '%env(string:DFS_DATABASE_COLLATION)%'
                url: '%env(string:DFS_DATABASE_URL)%'

# define the flysystem handler
oneup_flysystem:
    adapters:
        nfs_adapter:
            custom:
                service: ibexa.io.nfs.adapter.site_access_aware

# define ibexa handlers
ibexa_io:
    binarydata_handlers:
        nfs:
            flysystem:
                adapter: nfs_adapter
    metadata_handlers:
        dfs:
            legacy_dfs_cluster:
                connection: doctrine.dbal.dfs_connection

# set the application handlers
ibexa:
    system:
        default:
            io:
                metadata_handler: dfs
                binarydata_handler: nfs
