# Base configuration for Solr, for more options see: https://doc.ezplatform.com/en/latest/guide/search/#solr-bundle
# Can have several connections used by each Ibexa Repositories in ibexa.yaml

ibexa_solr:
    endpoints:
        endpoint0:
            dsn: '%env(string:SOLR_DSN)%'
            core: '%env(string:SOLR_CORE)%'
    connections:
        default:
            entry_endpoints:
                - endpoint0
            mapping:
                default: endpoint0
