parameters:
    siso_core.default.ses_swiftmailer:
        mailSender: noreply@ibexa.co
        mailReceiver: noreply@ibexa.co
        lostOrderEmailReceiver: noreply@ibexa.co
        contactMailReceiver: noreply@ibexa.co
        cancellationMailReceiver: noreply@ibexa.co
        shopOwnerMailReceiver: noreply@ibexa.co
    ses_eshop.forms.business.default_contact_recipient: noreply@ibexa.co
    ses_eshop.order.sales_contact: noreply@ibexa.co
    ses_eshop.lostorder_email: noreply@ibexa.co
    siso_paypal_payment.receiver_email: noreply@ibexa.co

    siso_core.siteaccess_group: ezdemo_site_clean_group
    apache_tika_path: '%kernel.project_dir%/bin/tika-app-1.20.jar'

    # commerce solr
#    siso_search.solr.host: '%env(SISO_SEARCH_SOLR_HOST)%'
#    siso_search.solr.port: '%env(SISO_SEARCH_SOLR_PORT)%'
#    siso_search.solr.core: '%env(SISO_SEARCH_SOLR_CORE)%'
#    siso_search.solr.path: '%env(SISO_SEARCH_SOLR_PATH)%'

    one_sky_api_key: my-one-sky-key
    one_sky_secret: my-onesky-password

    ewz_recaptcha_public_key: public_key
    ewz_recaptcha_private_key: private_key
